export const ContentRoutes = {
  Login: { name: "LoginPage", label: "로그인" },
  Main: { name: "Navigation", label: "메인" },
  HomePage: { name: "HomePage", label: "홈 화면(처음 화면)" },
  MapStack: { name: "MapPage", label: "지도 스택" },
  MapPage: { name: "MainPage", label: "지도 화면" },
  MapSearchPage: { name: "MapSearchPage", label: "지도 검색 화면" },
  StoreinfoPage: { name: "StoreinfoPage", label: "가게 정보 화면" },
  StoreListPage: { name: "StoreListPage", label: "가게 목록 화면" },
  OrderPage: { name: "OrderPage", label: "주문 화면" },
  WebViewPage: {name : "WebViewPage", label : "결제 화면"},
  TicketPage: { name: "TicketPage", label: "티켓 화면" },
  // OrderStack: {name: "OrderStack", label: "주문 스택"},
  OrderListPage: { name: "OrderListPage", label: "주문 내역 화면" },
  WriteReviewPage: { name: "WriteReviewPage", label: "리뷰 작성 화면" },
  OrderListStack: { name: "OrderListStack", label: "주문 내역 스택"},
  MyPageStack: { name: "MyPageStack", label: "마이페이지 스택"},
  MyPage: { name: "MyPage", label: "마이페이지"},
  BoardPage: { name: "BoardPage", label: "게시판 화면" },

};